from collections import deque

a = deque()
b = deque('abrakadabra', maxlen=4)
c = deque([1, 2, 3, 4])
print(a, b, c, sep='\n')

print('*' * 50)
d = deque([i for i in range(5)], maxlen=7)
print(d)
d.append(5)
print(d)
d.appendleft(6)
print(d)
d.extend([7, 8])
print(d)
d.extendleft([9, 10])
print(d)
spam = d.pop()
print(spam, d)
eggs = d.popleft()
print(eggs, d)
print(d[3])

print(list(d))
print(deque(list(d)))
